### ISSUE TITLE
MaxLength attribute and CustomColumnMapping

### ISSUE THREAD

**Issue by fvanoostrom** [gtaylor44/SqlBulkTools#1]
Great Tool! However, I did have some problems using the CustomColumnMapping: The [MaxLength()] attribute did not seem to be included when using this. 

Perhaps I'm not using it properly. Am I supposed to use it like this:
`.AddColumn(x => x.UserProfileId)

.CustomColumnMapping(x => x.UserProfileId, "ProfileId")`

Or can I exclude the first line?

Furthermore the connectionstring in the App.config was not used throughout the Test. Took me a while to find out why I couldn't connect... to your server ;)

**Comment by gtaylor44** [comment]
The CustomColumnMapping appears to be functioning correctly. The MaxLength attribute does not cause an issue (converts to nvarchar(x) in database) and I can't reproduce your error. Do you have a stack trace available? Your syntax looks fine. Just wondering... Is ProfileId in your table of type nvarchar or int?

**Comment by fvanoostrom** [comment]
Changed my code quite a bit, and now I can't reproduce it either. SQL Profiler shows the correct syntax. It was indeed a nvarchar/string
_ProfileId nvarchar(20)_

I think I might have mixed up two problems: 1. The Autofixture plug-in not recognizing the MaxLength for the autogenerated ProfileId-string. And 2. Me not understanding I have to include both 'AddColumn' and 'CustomColumnMapping'. Any reason you didn't create an overload of 'AddColumn' which includes the custom mapping?

**Comment by gtaylor44** [comment]
1. Make sure you're using version 2 as there have been a lot of improvements. I've used auto fixture only for testing purposes. I use a custom builder to randomly generate the strings. 

2. There is a new method 'AddAllColumns' so it still makes sense to have the 'CustomColumnMapping' method separate. I do however like your suggestion about having an optional parameter with 'AddColumn' as an alternative way to specify a custom column.

**Comment by fvanoostrom** [comment]
I've ran into the problem again. This time I was able to reproduce it in the Book Test example:

When I set up the bulkoperations with .BulkInsertOrUpdate() instead of .BulkInsert() the values of my 'decimal?' property are incorrectly put into the database: they will become 0.00 instead of 0.33 for example.

The value 0.33 is still visible in the collection, and after the BulkOperations Setup, and in the DataTable.

The creation of the temptable does not appear to be correct:
"CREATE TABLE #TmpTable([Title] nvarchar(256), [Price] decimal, [Description] nvarchar(2000), [ISBN] nvarchar(13), [PublishDate] datetime);"

Should be an [decimal](18, 2) as is used in the Books Table??

The problem seems to be the BulkOperationsHelper:
```
            foreach (DataRow row in schema.Rows)
            {
                actualColumns.Add(row["COLUMN_NAME"].ToString(), row["DATA_TYPE"].ToString());
                actualColumnsMaxCharLength.Add(row["COLUMN_NAME"].ToString(),
                    row["CHARACTER_MAXIMUM_LENGTH"].ToString());
            }
```

When using  .BulkInsert() they are inserted correctly??!

**Comment by gtaylor44** [comment]
Excellent.. Thanks for alerting me of this. A fix for determining decimal precision is on its way.

**Comment by gtaylor44** [comment]
Will be doing some more edge case testing with other data types tonight.

**Comment by gtaylor44** [comment]
Now done testing on pretty much all SQL data types (even those that are becoming deprecated). Thanks again for pointing this out.

**Comment by fvanoostrom** [comment]
Thanks for your fast responses and excellent work! Looking forward for an update :)

**Comment by gtaylor44** [comment]
No worries and thanks for your support. There will be a new update with some new features over the weekend.
