### ISSUE TITLE
Provide a way to connect an event handler to SqlBulkCopy when we use WithBulkCopyNotifyAfter

### ISSUE THREAD

**Issue by bpmerkel** [gtaylor44/SqlBulkTools#11]
Perhaps adjust the WithBulkCopyNotifyAfter() to take an Action<object, eventArgs> to connect to SqlBulkCopy so callers can be notified each interval of the load...

**Comment by gtaylor44** [comment]
Have added this functionality. WithBulkCopyNotifyAfter now takes IEnumerable<SqlRowsCopiedEventHandler> bulkCopyDelegates

This later gets set:
bulkCopyDelegates?.ToList().ForEach(x => bulkcopy.SqlRowsCopied += x);
