### ISSUE TITLE
Allow nullable identifier columns with MatchTargetOn?

### ISSUE THREAD

**Issue by Aigu** [gtaylor44/SqlBulkTools#13]
Hi
Great work with the SqlBulkTools!
Did you think about supporting nullable identifier columns with MatchTargetOn?
If you have a table with ISBN and another identifier like EAN_CODE where you can set both or only one each, it always results into an INSERT (if no index set).

The merge condition should have something like 
AND (a.EAN_CODE = b.EAN_CODE OR a.EAN_CODE IS NULL AND b.EAN_CODE IS NULL)

(from http://stackoverflow.com/questions/4509722/nulls-and-the-merge-statement-i-need-to-set-a-value-to-infinity-how)

**Comment by gtaylor44** [comment]
Have you checked out the "UpdateWhen" method and does this solve your issue? An example is in the documentation.

**Comment by gtaylor44** [comment]
By the way... Since your above example has 3 predicates you can chain the UpdateWhen method and it will track the order and concatenate them when you execute the transaction.
