### ISSUE TITLE
For bulk InsertOrUpdate allow exclude columns on update

### ISSUE THREAD

**Issue by sbaxterg** [gtaylor44/SqlBulkTools#18]
Hi,

I have a table that has the columns CreatedOn and ModifiedOn to maintain the history of changes. When I insert a new row I assign values to both columns, but on updates I just modify the ModifiedOn column.

It would be nice if is possible to indicate that a column should be excluded on update, perhaps something like RemoveColumn(<columnName>, Operation.Update)

**Comment by gtaylor44** [comment]
I will roll out an update for this within a few days.

**Comment by gtaylor44** [comment]
I will be calling it ExcludeColumnFromUpdate.. I did something similar already for the single entity Upsert method.

**Comment by gtaylor44** [comment]
If you update to 3.05 you will have access to this method. Here is the passing integration test to support the new feature:

![exclude_column_unit_test](https://cloud.githubusercontent.com/assets/11572604/20131459/b4b19fa0-a6b1-11e6-840c-7b9f8ce348ea.png)

**Comment by sbaxterg** [comment]
Many thanks!!!!
