### ISSUE TITLE
SqlBulkTools supports only from 2008 but not MSSQL 2005 ?

### ISSUE THREAD

**Issue by herurider** [gtaylor44/SqlBulkTools#22]
I've got an exception as,

'syntax is wrong near keyword 'INTO'' together with

'syntax is wrong near keyword 'with'', if this syntax is for common table or xmlnamespace, previous syntax should be closed with semi-colon.

Is this syntax is because of Server version 2005 ?

Thanks for your kind answer.

**Comment by gtaylor44** [comment]
Yes, MERGE statement requires SQL Server >= 2008

Time to upgrade :)

**Comment by herurider** [comment]
Oh, Time to upgrade sounds witful :)
Thanks for your quick & kind answer.

Unfortunately, my application is sub-application and I have to follow the server version of main-application..

Hope your great achievements !
