### ISSUE TITLE
Exception while updating 

### ISSUE THREAD

**Issue by sandeip-yadav** [gtaylor44/SqlBulkTools#23]
Cannot resolve the collation conflict between "Turkish_CI_AS" and "SQL_Latin1_General_CP1_CI_AS" in the equal to operation.

**Comment by gtaylor44** [comment]
Try setting the collation on the MatchTargetOn column(s)

e.g. 
..
BulkInsertOrUpdate()
.SetCollationOnColumn(column, "DATABASE_DEFAULT")
..
