### ISSUE TITLE
How to deal collation problems ?

### ISSUE THREAD

**Issue by abhilashkm1988** [gtaylor44/SqlBulkTools#24]
Hai ,

 I don't know weather its an issue or not. I'm getting the following error while bulk updating two tables
in a single transaction scope!

Cannot resolve the collation conflict between \"Latin1_General_CI_AI\" and \"SQL_Latin1_General_CP1_CI_AS

Please help me to solve this issue!

**Comment by gtaylor44** [comment]
Try setting the collation on the MatchTargetOn column(s) that are of type string. 

e.g.

BulkUpdate()
.SetCollationOnColumn(column, "DATABASE_DEFAULT")

Let me know how that goes.

**Comment by gtaylor44** [comment]
And by string I mean textual data types e.g. nvarchar, varchar, char. You can't compare two different collations of textual data type without casting.
