### ISSUE TITLE
BulkInsertOrUpdate()

### ISSUE THREAD

**Issue by olympicdream** [gtaylor44/SqlBulkTools#25]
Hi,

I want to use BulkInsertOrUpdate() method for generic lists. I have multiple lists and i don't want to write this method for each list. But I can't resolve MatchTargetOn() part. here is my code;

  private void InsertOrUpdateDataToSQL<T>(IList<T> list, string tableName, PropertyInfo propertyInfo)
        {
            try
            {
                var bulkOperation = new BulkOperations();
                using (var transaction = new TransactionScope())
                {
                    using (var connection = new SqlConnection(_entities.Database.Connection.ConnectionString))
                    {
                        bulkOperation.Setup<T>()
                            .ForCollection(list)
                            .WithTable(tableName)
                            .AddAllColumns()
                            .BulkInsertOrUpdate()
                            .SetIdentityColumn(x => propertyInfo.Name)
                            .MatchTargetOn(x => property.Name)
                            .Commit(connection);
                    }
                    transaction.Complete();
                }
            }
            catch (Exception ex)
            { 
                throw ex;
            }
        }

SetIdentityColumn() is not making any problem, bu MatchTargetOn() is not working. Can you help me?

Thanks.

**Comment by gtaylor44** [comment]
Try this:

        private void InsertOrUpdateDataToSQL<T>(IList<T> list, string tableName, PropertyInfo propertyInfo)
        {
            try
            {
                var bulkOperation = new BulkOperations();
                using (var transaction = new TransactionScope())
                {
                    using (SqlConnection connection = new SqlConnection(ConfigurationManager
                    .ConnectionStrings["SqlBulkToolsTest"].ConnectionString))
                    {
                        bulkOperation.Setup<T>()
                        .ForCollection(list)
                        .WithTable(tableName)
                        .AddAllColumns()
                        .BulkInsertOrUpdate()
                        .SetIdentityColumn(x => propertyInfo.Name)
                        .MatchTargetOn(x => propertyInfo.Name)
                        .Commit(connection);
                    }
                    transaction.Complete();
                }
            }
            catch (Exception ex)
            {
                throw ex;
            }
        }

**Comment by olympicdream** [comment]
Thank you for your answer. But my code was like yours. I should make a mistake while copying it to here.

private void InsertOrUpdateDataToSQL<T>(IList<T> list, string tableName, PropertyInfo propertyInfo)
        {
            try
            {
                var bulkOperation = new BulkOperations();
                using (var transaction = new TransactionScope())
                {
                    using (var connection = new SqlConnection(_entities.Database.Connection.ConnectionString))
                    {
                        bulkOperation.Setup<T>()
                            .ForCollection(list)
                            .WithTable(tableName)
                            .AddAllColumns()
                            .BulkInsertOrUpdate()
                            .SetIdentityColumn(x => propertyInfo.Name)
                            .MatchTargetOn(x => propertyInfo.Name)
                            .Commit(connection);
                    }
                    transaction.Complete();
                }
            }
            catch (Exception ex)
            { 
                throw ex;
            }
        }

When I use propertyInfo.Name, it is being occured an error like "The definition for column 'Name' must include a data type.". If I use .MatchTargetOn(x => propertyInfo) the error changes like "The definition for column 'propertyInfo' must include a data type."

My generic list type has two properties (types are string and one of them is primary key in SQL table).

Is there any to solve it?

Thanks again.

**Comment by gtaylor44** [comment]
I've just done some debugging and found the same result. This would require an update of the library to handle situations like this. It is possible but a bit of an edge case scenario. Is there any way you can make the setup strongly typed and use MatchTargetOn for an actual property?

**Comment by olympicdream** [comment]
I have 27 tables just for now :) I needed a fast tool. So I decided to use SqlBulkTools. It actually works. I appreciate you. It performance is really perfect for me. But I need to use something which supports dynamically coding. I tryed to solve it with datatables in SqlBulkTools but I saw that it is only supporting to select data from SQL. I don't want to return to SqlBulkCopy but I can use it until SqlBulkTools has an update for this issue :)
Thank you for your helps.

**Comment by gtaylor44** [comment]
I had a request before to make an overload for MatchTargetOn and SetIdentityColumn to take a string
e.g. 

.SetIdentityColumn("Id")
.MatchTargetOn("ISBN")

Would this solve your problem?

**Comment by gtaylor44** [comment]
I have published version 3.1.1

New version has an overload for MatchTargetOn and SetIdentityColumn to take a string. 

Hope this helps.

**Comment by olympicdream** [comment]
I was just about to answer you. I tryed like your example but it doesn't accept any string value. I have last version (3.1.1) of tool. I have should made some mistake while updating it. I will reinstall it.

**Comment by olympicdream** [comment]
I am sorry. I had v3.1.0. I updated and tryed with sending column names as string. It worked.
Thank you so much for your help.

**Comment by gtaylor44** [comment]
Were your entities persisted to your database table(s) too?

**Comment by olympicdream** [comment]
Yes, alll table data is persisted. I've tested them. It updates and inserts if record doesn't exist in table.
Thanks.

**Comment by olympicdream** [comment]
I am sorry again. It updates successfully. But if I deleted one row from table, an exception is happening in method. I've checked wrong table before.

**Comment by gtaylor44** [comment]
Can you provide the stacktrace of the exception?

**Comment by olympicdream** [comment]
Hi,

I upgraded SqlBulkTools to 4.03 version. I want to use BulkInsertOrUpdate() or BulkDelete() methods as generic. Before this version I was able to set parameters as string type for SetIdentityColumn()/MatchTargetOn() methods. But now I can't. Can you help me about this? 

Thank you.

**Comment by olympicdream** [comment]
Hi, I finally managed to use methods as generic. I sent predicate as parameter. But I have another question. I've asked it before. Sorry for overdue response. BulkInsertOrUpdate method still throws exception when new rocerd inserting. It updates the current row successfully but it doesn't add any new record. Can you please help me?

Thank you for your time.

**Comment by gtaylor44** [comment]
This is an SqlException. Your column doesn't allow nulls. Either ignore the column in your setup or make the column nullable in your database table.

To ignore from setup:
`.RemoveColumn(x => x.Column1)`

To make column nullable:
`ALTER TABLE [XXX.dbo.Table1] ALTER COLUMN [Column1] INTEGER NULL`
