### ISSUE TITLE
BulkUpdate SetIdentityColumn issue

### ISSUE THREAD

**Issue by FlxGen** [gtaylor44/SqlBulkTools#27]
Using the code below I'm getting the error:  " Cannot update identity column 'Key'. SQLBulkTools requires the SetIdentityColumn method to be configured if an identity column is being used. Please reconfigure your setup and try again."

Have I missed something from readme?  

    bulkOperations.Setup<Model>()
                        .ForCollection(collection)
                        .WithTable("Table")
                        .AddAllColumns()
                        .BulkUpdate()
                        .SetIdentityColumn(x => x.Key)
                        .MatchTargetOn(x => x.Key)
                        .Commit(conn);`

**Comment by gtaylor44** [comment]
Can you confirm that the property you're setting with SetIdentityColumn with is indeed an identity column? This exception is only thrown if you attempt to update an identity column which is an illegal action in SQL. The purpose of SetIdentityColumn is to exclude the column from being updated. The MatchTargetOn expression is fine and should not cause an issue. Check that the property 'key' is in fact an identity column. 

Another way to solve this would be to use AddColumn for each column you want to update and of course exclude the 'key' column.

**Comment by gtaylor44** [comment]
And just for reference...

See error code 8102
http://www.sql-server-helper.com/error-messages/msg-8001-8500.aspx

`            catch (SqlException e)
            {
                for (int i = 0; i < e.Errors.Count; i++)
                {
                    // Error 8102 and 544 is identity error. 
                    if (e.Errors[i].Number == 544 || e.Errors[i].Number == 8102)
                    {
                        // Expensive but neccessary to inform user of an important configuration setup. 
                        throw new IdentityException(e.Errors[i].Message);
                    }
                }

                throw;
            }`
