### ISSUE TITLE
CustomColumnMapping on BulkDelete/BulkUpdate

### ISSUE THREAD

**Issue by squall8fr** [gtaylor44/SqlBulkTools#29]
Hi, 

Could it be possible to add CustomColumnMapping() function on BulkDelete/BulkUpdate (also with the "When" versions). The compiler seems to accept it but it crashes when running.

```
    bulk.Setup<WeightProcess>()
                            .ForCollection(CageWeights)
                            .WithTable("Cage Weight")
                            .AddColumn(x=>x.AnimalId)
                            //.CustomColumnMapping(x => x.AnimalId, "Animal ID")
                            .BulkDelete()
                            .MatchTargetOn(x => x.AnimalId)
                            .Commit(conn);   
```
Thanks for your work !

**Comment by gtaylor44** [comment]
I've applied some fixes to the AddColumn method and incremented version to 4.3.1

Note that the API has changed a bit. In the later versions, AddColumn has an overload for a custom column mapping. CustomColumnMapping method is now only available after AddAllColumns(). Your above example will not compile in recent versions. 

Your setup should look something like this now:

```
    bulk.Setup<WeightProcess>()
                            .ForCollection(CageWeights)
                            .WithTable("Cage Weight")
                            .AddColumn(x=> x.AnimalId, "Animal ID")
                            .BulkDelete()
                            .MatchTargetOn(x => x.AnimalId)
                            .Commit(conn);   
```

**Comment by squall8fr** [comment]
I was using v4.3.0, now it compiles with the latest version :)

This overload will be very useful, thank you :)
