### ISSUE TITLE
Merge on nullable columns with MatchTargetOn

### ISSUE THREAD

**Issue by crazyslon** [gtaylor44/SqlBulkTools#30]
Hi!
Thank's for your library!
I'm using BulkInsertOrUpdate method with MatchTargetOn on nullable guid column like
.MatchTargetOn(x => x.NullableColumn)

Sql Server when comparing two null columns by '=' always return false. So merging expression like :
AND [Target].[NullableColumn] = [Source].[NullableColumn] AND ...
return false in this case. So data is inserted instead of updating.

Merge condition should be like 
AND ([Target].[NullableColumn] = [Source].[NullableColumn] OR ([Target].[NullableColumn] IS NULL AND [Source].[NullableColumn] IS NULL))

I know about issue https://github.com/gtaylor44/SqlBulkTools/issues/13 but i don't understand how to resolve this problem using UpdateWhen.

**Comment by gtaylor44** [comment]
This should be possible to add as a feature. So when UpdateWhen, you want to be able to chain either an AND or an OR one or more times and wrap all in parentheses?

**Comment by crazyslon** [comment]
I think it's pretty common situation and may be for nullable property types  need to use construction like this
AND ([Target].[NullableColumn] = [Source].[NullableColumn] OR ([Target].[NullableColumn] IS NULL AND [Source].[NullableColumn] IS NULL)) by default? 

Because merge query like this 
AND [Target].[NullableColumn] = [Source].[NullableColumn] not enough.

**Comment by gtaylor44** [comment]
Sorry for misunderstanding. Yes this should be accounted for and ill start work on it shortly. Thanks for finding this.

**Comment by gtaylor44** [comment]
This change has been made. Could you please update to version 4.3.2 and confirm you're happy with it. The new behaviour is as you have described. If the column is nullable, add an additional condition to check if the source and target are null are both null. This condition is not added if the column is NOT NULL. Let me know how it goes so I can close this issue.

**Comment by crazyslon** [comment]
Thanks for Your reply, but class BuildJoinConditionsForInsertOrUpdate needs small fix in method
BuildJoinConditionsForInsertOrUpdate. In for loop using BuildNullCondition(updateOn[0],...). It seems to be 
BuildNullCondition(updateOn[i],...)

**Comment by gtaylor44** [comment]
This has been fixed in 4.3.3

**Comment by crazyslon** [comment]
Thank you very much, now it's all right

**Comment by gtaylor44** [comment]
Great to hear... Have a nice day/evening
