### ISSUE TITLE
Enum in Model

### ISSUE THREAD

**Issue by aliebrahimi2015** [gtaylor44/SqlBulkTools#31]
How to use Enum Field in Model 
public enum DepartmentNames 
{ 
    English, 
    Math, 
    Economics 
}     
 
public class Department 
{ 
    public int DepartmentID { get; set; } 
    public DepartmentNames Name { get; set; } 
    public decimal Budget { get; set; } 
}
thank you

**Comment by gtaylor44** [comment]
Add the column as you normally would with AddColumn or AddAllColumns. If there is a column in your table named 'DepartmentNames' with the type int then it will work fine. In the above example, English will be 0, Math 1 and Economics 2.
