### ISSUE TITLE
geometry sql data type

### ISSUE THREAD

**Issue by amjadriazmsncom** [gtaylor44/SqlBulkTools#32]
Hi,

Having trouble to use BulkInsert with any table has geometry type column?
Am i missing something? or is it a issue with the Tool?

Regards

**Comment by gtaylor44** [comment]
SqlGeometry has not been tested for, this is an issue with the library. Is it possible to provide an example of your model and some mock data?

**Comment by amjadriazmsncom** [comment]
That's great, Thanks for your help!!

I think it will be helpful for many :) I will update all readers soon on my test run.

Cheers!

**Comment by gtaylor44** [comment]
I haven't tested this yet and it has not been published. Do you have some typical test data for this data type?

**Comment by amjadriazmsncom** [comment]
Test Data attached.

I recon once you released the latest library then property type will be SqlGeometry

   public class TestClass
    {
        public decimal? Latitude { get; set; }
        public decimal? Longitude { get; set; }
        public SqlGeometry LatLongGeom { get; set; }
    }

In case CSV does not work then

you could use below function to generate Points from Long and Lat

for example if you have long and Lat column add geometry column (computed column) and use below formula will generate the correct points i think good for testing

This function can be improved but will do the job for now 

([geometry]::STGeomFromText(((('POINT ('+CONVERT([nvarchar](1000),[longitude]))+' ')+CONVERT([nvarchar](2000),[Latitude]))+')',(4326)))

I hope it helps. otherwise let me know in which shape do you need test data happy to provide you.

Thanks for your help.

**Comment by amjadriazmsncom** [comment]
[SampleData.zip](https://github.com/gtaylor44/SqlBulkTools/files/839859/SampleData.zip)

**Comment by gtaylor44** [comment]
Please update to the latest version 4.3.4

I tested the first row of SampleData.zip. Database table column was of type 'geometry' and c# model property was of type SqlGeometry

SqlGeometry TestSqlGeometry = SqlGeometry.Point(-2.74612, 53.881238, 4326)

Had value in db of: 0xE6100000010CD52137C30DF805C009FF2268CCF04A40 (which correlates the cell C2 in sample data)

Let me know if you're happy with this and I will close the issue.

**Comment by amjadriazmsncom** [comment]
Just a suggestion:

I am currently working on a scenario where I required to move massive dataset across based on Business rules once data bulk inserted then I need to delete data from the source as well, to keep application running without any breakage. So I am using BulkInsert and BulkDelete as two separate process, using Transaction scope though. But experience some inconsistency between data insertion and deletion, that is just because of the complex business rule applied in bulk insert. I have managed to satisfy business requirements.

But I have a suggestion if we could add functionality for example BulkMove that deal Data Move scenario in transaction context would make library even more useful 

appreciated your effort mate.

Cheers!

**Comment by gtaylor44** [comment]
Glad that it's working and thanks for your feedback. 

An operation like BulkMove would involve a lot of work that would outweigh the benefits. Nobody else has asked for this feature. In saying that, if the tide changes, it will be considered. I'm unsure about your comment about inconsistencies. If you nest both BulkInsert and BulkDelete in the same TransactionScope with the same SqlConnection, you can be assured that if the second transaction fails, both transactions will be rolled back. Everything within TransactionScope is an atomic transaction.
