### ISSUE TITLE
error when using schema other than dbo

### ISSUE THREAD

**Issue by specedm** [gtaylor44/SqlBulkTools#35]
receive below error when I try to bulkinsertorupdate and the withtable has the schema in it.

Error: Table name 'schema.table' with schema name 'dbo' not found. Check your setup and try again.

**Comment by specedm** [comment]
sorry needed to use the WithSchema property

**Comment by gtaylor44** [comment]
schema.table is technically correct. I will post an update later to accept this as valid input (removing the need to call WithSchema).

**Comment by specedm** [comment]
Thanks Greg. using v4.4.0 and still have the same results.

**Comment by gtaylor44** [comment]
Including schema name in WithTable method will work from version 4.43

example: 
```
WithTable("schema.table")
WithTable("[schema].[table]")
```
