### ISSUE TITLE
Use Microsoft.SqlServer.Types from Nuget

### ISSUE THREAD

**Issue by igoree** [gtaylor44/SqlBulkTools#36]
Microsoft.SqlServer.Types is available as a [Nuget package](https://www.nuget.org/packages/Microsoft.SqlServer.Types/). It will be nice if you replace the direct reference with a Nuget dependency because Microsoft.SqlServer.Types isn't installed by default on servers

**Comment by gtaylor44** [comment]
Ok will do. For what operation did you experience the unresolved reference?

**Comment by gtaylor44** [comment]
Version 4.41 includes the dependency Microsoft.SqlServer.Types

Sorry for the inconvenience.

**Comment by igoree** [comment]
We experienced the unresolved reference in one of our internal libraries that looks for types in referenced assemblies. This functionality is legacy but we cannot remove it now. Thank you for your help!
