### ISSUE TITLE
Error on BulkInsertOrUpdate

### ISSUE THREAD

**Issue by diego81b** [gtaylor44/SqlBulkTools#39]
Hi,
with the latest version using:

```
bulk.Setup<Company>()
    .ForCollection(companies)
    .WithTable("TB_COMPANY_BKP")
    .WithSchema("DATI")
    .AddColumn(x => x.Id, "ID_COMPANY")
    .AddColumn(x => x.Name, "NAME")
    .AddColumn(x => x.Email, "EMAIL")
    .AddColumn(x => x.PhoneNumber, "PHONE_NUMBER")
    .BulkInsertOrUpdate()
    .SetIdentityColumn(x => x.Id)
    .MatchTargetOn(company => company.Id)
    .Commit(conn);
```
i'm getting : "Cannot update identity column 'ID_COMPANY'. SQLBulkTools requires the SetIdentityColumn method to be configured if an identity column is being used. Please reconfigure your setup and try again."

with the same model and configuration BulkInsert works well
what i'm doing wrong?

Thanks.
Diego

**Comment by gtaylor44** [comment]
The custom mapping on Id is likely to be the culprit. Thank you for reporting this issue. I will post a fix for this shortly.

**Comment by gtaylor44** [comment]
I was able to reproduce this bug and it has been resolved. Please update to version 4.45. If you have any further issues, let me know. 

Kind Regards,
Greg
