### ISSUE TITLE
any plans on adding 'AND' clause?

### ISSUE THREAD

**Issue by patil-nileshb** [gtaylor44/SqlBulkTools#4]
@gtaylor44 do you haveany plans to implement AND at least 
 [ WHEN NOT MATCHED BY SOURCE [ AND clause_search_condition ]
Thank you

**Comment by gtaylor44** [comment]
I've thought about this feature and it's more of a long term plan. I'm working on other projects at the moment and lack the time needed.  Currently, you would need to do the filtering in-memory. As a community project, I'm hoping that others like yourself will contribute.

**Comment by gtaylor44** [comment]
This feature has now been added. See DeleteWhen method in docs.
