### ISSUE TITLE
Incorrect syntax near the keyword 'INTO'

### ISSUE THREAD

**Issue by tomotrepo** [gtaylor44/SqlBulkTools#45]
Hi

I've made simple example. While .BulkInsert works fine, .BulkInsertOrUpdate throws what's in title.

Here is the code

`
protected void Page_Load(object sender, EventArgs e)
{
	string connString = "xxx";

	var bulk = new BulkOperations();
	var dtOps = new DataTableOperations();

	List<Item> items = new List<Item>();
	items.Add(new Item("aaa1", "bbb1", "ccc1"));
	items.Add(new Item("aaa2", "bbb2", "ccc2"));
	items.Add(new Item("aaa3", "bbb3", "ccc3"));
	items.Add(new Item("aaa4", "bbb4", "ccc4"));
	items.Add(new Item("aaa5", "bbb5", "ccc5"));
	items.Add(new Item("aaa6", "bbb6", "ccc6"));
	items.Add(new Item("aaa7", "bbb7", "ccc7"));
	items.Add(new Item("aaa8", "bbb8", "ccc8"));
	items.Add(new Item("aaa9", "bbb9", "ccc9"));

	using (TransactionScope trans = new TransactionScope())
	{
		using (SqlConnection conn = new SqlConnection(connString))
		{
			bulk.Setup<Item>()
					.ForCollection(items)
					.WithTable("test1")
					.AddAllColumns()
					.BulkInsertOrUpdate()
					.MatchTargetOn(x => x.id)
					.Commit(conn);
		}

		trans.Complete();
	}
}

public class Item
{
	public string id { get; set; }
	public string name1 { get; set; }
	public string name2 { get; set; }

	public Item(string id, string name1, string name2)
	{
		this.id = id;
		this.name1 = name1;
		this.name2 = name2;
	}
}
`

id column is intented string without Identity

Best regards

**Comment by gtaylor44** [comment]
I can't reproduce this. Are you using the latest version 4.49? 

![image](https://cloud.githubusercontent.com/assets/11572604/24792217/6b851d3c-1bc0-11e7-82f2-a28a9a2ac05d.png)

![image](https://cloud.githubusercontent.com/assets/11572604/24792255/90ca7fba-1bc0-11e7-86af-81976b5d11e3.png)

**Comment by tomotrepo** [comment]
Thnx for taking your time. Your answer give me to think, to check sql version. On testing machine I've still 2005. When move on higher, everythig works. Now I'll try with some thousand records :)

Best regards

**Comment by gtaylor44** [comment]
Yes that's right. MERGE is not supported in SQL Server 2005... I should've realised this.

I've added version checking to throw a more useful exception when legacy SQL Server version is used which will be included in the next release.
