### ISSUE TITLE
Usable for an existing DataTable?

### ISSUE THREAD

**Issue by jhorv** [gtaylor44/SqlBulkTools#8]
Sorry to write this as an issue, thought it'd be the fastest way.
I'm dealing with DataTables that don't have corresponding .NET types.  I can't find anything in the API to do bulk operations with these already-built DataTables.  Am I missing something, or is that not supported?

Thanks!  Nice code!

**Comment by gtaylor44** [comment]
Hey Jhorv, 

The functionality to use an existing data table isn't available at the moment. I will keep this in mind for future versions.

**Comment by gtaylor44** [comment]
I'm going to spend some time this week on this issue.

**Comment by gtaylor44** [comment]
I'm still working on this issue and will update you when I have something.

**Comment by jhorv** [comment]
Great, thanks for the effort!

**Comment by gtaylor44** [comment]
Sorry, I can't complete this requirement. Please use stored proc for your requirement instead.
