### ISSUE TITLE
Need an overload of AddColumn to accept a string argument of the column name

### ISSUE THREAD

**Issue by bpmerkel** [gtaylor44/SqlBulkTools#9]
... useful when composing mappings from a collection of strings

**Comment by gtaylor44** [comment]
Could you please provide an example of what you're trying to achieve?

**Comment by bpmerkel** [comment]
Something like this in SingularColumnSelect.cs. Perhaps refactor the current AddColumn to call this too:
`        /// <summary>
        /// Add each column that you want to include in the query. Only include the columns that are relevant to the 
        /// procedure for best performance. 
        /// </summary>
        /// <param name="columnName">Column name as represented in database</param>
        /// <returns></returns>
        public SingularColumnSelect<T> AddColumn(string columnName)
        {
            _columns.Add(columnName);
            return this;
        }`

**Comment by gtaylor44** [comment]
I will put this in my backlog of things to do. Is this mainly a convenience feature?

**Comment by gtaylor44** [comment]
I have decided against this feature because each setup requires an object or list of objects. I would prefer to keep all setups strongly typed without an option for magic strings.
